title: LJ Connolly | Research
description: Hey! Iâ€™m LJ. Welcome to my little corner of the internet.
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

baseurl: "/intro-to-TandT"
url: "https://ljconnolly.github.io"